// Simple config for Jenkins to spawn a task on the master node
pipeline {
    // This triggers the 'master' node, since Jenkins by default runs on its own node
    // Note that `agent { label 'master' }` would be equivalent if the master was labelled correctly
    agent any
    stages {
        stage('Build') {
            steps {
                // This will print the instance-id of the node running this build
                // In this case it should be the instance on which Jenkins is run
                // See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
                sh 'curl http://169.254.169.254/latest/meta-data/instance-id && echo'
            }
        }
    }
}
