# Alacritty config
#
# man 5 alacritty

import = [
    "~/.config/alacritty/fall.toml"
]

[bell]
animation = "EaseOutSine"
color = "#dba40d"
duration = 300

[cursor]
blink_interval = 250
thickness = 0.5
unfocused_hollow = true
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Block"
# unfocused_hollow = true

[font]
size = 15.0

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

# [[keyboard.bindings]]
# action = "ToggleSimpleFullScreen"
# key = "Return"
# mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "v"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "c"
mods = "Control|Shift"
action = "Copy"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

# This doesn't work right
# Use mouse middle to paste
# [[mouse.bindings]]
# action = "Copy"
# mouse = "Left"

[shell]
program = "/usr/bin/bash"
# program = "/opt/homebrew/bin/bash"
args = ["--login"]

[window.padding]
x = 10
y = 10
