// Test case for a broken Jenkins config which spawns infinite nodes
pipeline {
    // This triggers a node which is marked to not connect and thus cascade spawn
    agent { timeout(20) { label 'slave && broken'} }
    stages {
        stage('Build') {
            steps {
                // This will print the instance-id of the slave EC2 to the Jenkins console log
                // As proof that this is run inside the slave and not the master
                // See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
                sh 'curl http://169.254.169.254/latest/meta-data/instance-id && echo'
            }
        }
    }
}
